version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: sync git repo
          command: |
            git clone --depth 1 https://github.com/joway/blog.git public
            find ./public -not -name '.git' -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf --
      - run:
          name: build site
          command: |
            make site
      - deploy:
          name: push newest site
          command: |
            export msg=$(git log --pretty=format:%s -1)
            cd public
            git config credential.helper 'cache --timeout=120'
            git config user.email "joway.w@gmail.com"
            git config user.name "Joway.CI"
            git add .
            git commit --allow-empty -m "$msg"
            git push -q https://${GITHUB_TOKEN}@github.com/joway/blog.git master --force
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: github
